config/routes.rb
Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check
  resources :connectors, only: %i[index show]
  resources :evses, only: %i[index show]
  resources :locations, only: %i[index show]
  resources :credentials, only: %i[index show]
  resources :logs, only: %i[index show]
  resources :client_infos, only: [:index]
  get 'locations/show'
  mount Ocpi::Engine => '/'
  get '/' => 'home#index'
  get '/table' => 'home#table'
  root to: 'home#index'
  devise_for :users
  # Admin routes
  namespace :admin do
    resources :partners, controller: 'partner/partners', only: %i[index show edit update] do
      member do
        put '/push/', to: 'partner/partners#push_charger_group', as: :push_charger_group
        put '/download/', to: 'partner/partners#download_charger_group', as: :download_charger_group
      end

      resources :oauth_applications, controller: 'partner/oauth_applications', except: %i[index destroy] do
        member do
          get :approve
          get :validate
          post :receive_push
          get :ocpi_disconnect
          get :ocpi_modules
        end
      end
    end

    resources :admins
  end

  devise_for :partners, class_name: 'Partner::Partner', controllers: {
    sessions: 'partner/devise/sessions',
    passwords: 'partner/devise/passwords',
    registrations: 'partner/devise/registrations',
    confirmations: 'partner/devise/confirmations',
    unlocks: 'partner/devise/unlocks'
  }

  use_doorkeeper scope: 'partner' do
    controllers applications: 'partner/oauth_applications'
    controllers authorizations: 'partner/authorizations'
    controllers tokens: 'partner/tokens'
  end

  namespace :partner do
    root 'dashboard#index'
    post '/tokens/ocpi_request' => 'tokens#ocpi_request'
    post '/tokens/ocpi_connect' => 'tokens#ocpi_connect'
    delete '/tokens/ocpi_disconnect' => 'tokens#ocpi_disconnect'
  end
end

app/models/partner/developer_partner.rb
class Partner::DeveloperPartner < ApplicationRecord
  belongs_to :partner
  belongs_to :application
end

app/controllers/admin/partner/oauth_applications_controller.rb
class Admin::Partner::OauthApplicationsController < AdminController
  before_action :set_partner
  before_action :set_application

  def show
    @pagy, @access_tokens = pagy(@application.access_tokens, items: 5)
  end

  def edit; end

  def update
    if @application.update(application_params)
      redirect_to admin_partner_oauth_application_path(partner_id: @partner.id, id: @application.id),
                  flash: { success: 'Application successfully updated.' }
    else
      render :edit
    end
  end

  def approve
    if @application.present?
      @application.update(approved_by_admin: true)
      # @partner.create_user_charging_session if @partner.user.blank?
      redirect_to admin_partner_oauth_application_path(partner_id: @partner.id, id: @application.id),
                  flash: { success: 'Application successfully approved.' }
    else
      redirect_to admin_partner_path(@partner), flash: { error: 'Application failed to approve.' }
    end
  end

  def validate
    # verify their version
    ocpi_configuration = Ocpi::Application::Credentials::Services::FetchVersion.new(token: @application.credentials_token_a)
    result = ocpi_configuration.call(url: @application.ocpi_version_endpoint)
    if ocpi_configuration.valid?
      @application.update(ocpi_validation_status: :ocpi_valid)
      flash[:success] = I18n.t(:notice, scope: %i[doorkeeper flash applications ocpi valid])
    else
      flash[:error] = I18n.t(:notice, scope: %i[doorkeeper flash applications ocpi invalid])
    end
    redirect_to admin_partner_oauth_application_path(partner_id: @partner.id, id: @application.id)
  rescue StandardError => e
    flash[:error] = I18n.t(:notice, scope: %i[doorkeeper flash applications ocpi invalid]) + ' => ' + e.to_s
    redirect_to admin_partner_oauth_application_path(partner_id: @partner.id, id: @application.id)
  end

  def receive_push
    if @application.update(receive_push_model: params[:receive_push_model])
      status = params[:receive_push_model] == 'true' ? 'resumed' : 'paused'
      redirect_to admin_partner_oauth_application_path(partner_id: @partner.id, id: @application.id),
                  flash: { success: "Push Model successfully #{status}" }
    else
      redirect_to admin_partner_oauth_application_path(partner_id: @partner.id, id: @application.id),
                  flash: { error: 'Something went wrong' }
    end
  end

  def ocpi_modules
    @their_token = Ocpi::Domain::Credentials::Models::Credential.find params[:ocpi_credentials_id]
    @ocpi_modules = Ocpi::Domain::Versions::Models::Endpoint.joins(
      version_detail: {
        version: :credential
      }
    )
                                                            .where('ocpi_credentials.id = ?', params[:ocpi_credentials_id])
                                                            .order(identifier: :asc)
  end

  private

  def set_partner
    @partner = ::Partner::Partner.find_by_id(params[:partner_id])
  end

  def set_application
    @application = @partner.oauth_applications.find_by_id(params[:id])
  end

  def application_params
    params.require(:partner_application).permit(:name, :redirect_uri, :scopes, :confidential, :payment_gateway_webhook,
                                                :status_notification_webhook)
  end
end

app/controllers/admin/partner/partners_controller.rb
class Admin::Partner::PartnersController < AdminController
  before_action :set_partner, only: %i[show edit update]

  def index
    @q = Partner::Partner.ransack(params[:q])
    @pagy, @partners = pagy(@q.result(distinct: true), items: 5)
  end

  def show
    @applications = @partner.oauth_applications.order(id: :desc) # .page(params[:page])
  end

  def edit; end

  def update
    if @partner.update(partner_params)
      # @partner.generate_partner_charger_group(params[:partner_charger_groups])
      redirect_to admin_partners_path, flash: { success: 'Partner updated successfully.' }
    else
      render :edit
    end
  end

  private

  def set_partner
    @partner = Partner::Partner.find_by(id: params[:id])
  end

  def partner_params
    params.require(:partner_partner).permit(:code, :name, :address, :city, :state, :country, :postcode,
                                            :overview, :registration_no, :website_url, :logo, :email, :mobile_phone, :user_id, :party_id,
                                            :country_code, :ocpi_percentage_fee, :charger_group_option, :partner_charger_groups)
  end
end

app/controllers/partner/authorizations_controller.rb
class Partner::AuthorizationsController < Doorkeeper::AuthorizationsController
  skip_forgery_protection
  before_action :get_application, only: %i[create destroy]
  before_action :previous_path

  def create
    if @application.approved_by_admin?
      authorization = ::Partner::AccessGrant.new(redirect_uri: @application.redirect_uri,
                                                 application_id: @application.id, expires_in: 3600, resource_owner_id: @application.owner.id, scopes: @application.scopes)
      @authorization = if authorization.save
                         { message: 'Your application authorized!', is_success: true,
                           authorization_code: authorization.token }
                       else
                         { message: 'Something went wrong!', is_success: false, authorization_code: nil }
                       end
    else
      @authorization = { message: 'You do not have authorization to access. <br> Waiting for Approval',
                         is_success: false, authorization_code: nil }
    end
  end

  def show
    @access_grant = ::Partner::AccessGrant.find_by_token(params[:code])
  end

  def destroy
    access_grant = ::Partner::AccessGrant.find_by_id(params[:id])
    access_grant.destroy
    redirect_to oauth_application_path(@application.id), notice: 'Successfully destroyed'
  end

  private

  def get_application
    @application = ::Partner::Application.find_by_uid(params[:client_id])
    return unless @application.blank?

    @authorization = { message: 'Application not found', is_success: false,
                       authorization_code: nil }
  end

  def previous_path
    @previous_path = params[:previous_path]
  end
end

app/controllers/partner/base_controller.rb
class Partner::BaseController < ActionController::Base
  include Pagy::Backend

  layout 'partner'
  before_action :authenticate_partner!

  def authenticate_partner!
    return if partner_signed_in?

    redirect_to new_partner_session_path
  end

  def render_turbo_flash
    turbo_stream.update('flash', partial: 'shared/flash')
  end
end

app/controllers/partner/dashboard_controller.rb
class Partner::DashboardController < Partner::BaseController
  def index
    current_partner_apps = current_partner.applications.pluck(:id)
    # unless current_partner_apps.blank?
    #   @api_req_log_today = ::Partner::ApiRequestLog.by_today(current_partner_apps).page(params[:by_today]).per(5)
    #   @api_req_log_this_week  = ::Partner::ApiRequestLog.by_this_week(current_partner_apps).page(params[:by_this_week]).per(5)
    #   @api_req_log_this_month = ::Partner::ApiRequestLog.by_this_months(current_partner_apps).page(params[:by_this_months]).per(5)
    # end
  end

  def arl_details
    @api_requ_log = ::Partner::ApiRequestLog.find_by_id(params[:arl_id])
  end
end

app/controllers/partner/members_controller.rb
class Partner::MembersController < Partner::BaseController
  layout 'partner'
  skip_before_action :authenticate_partner!, only: %i[new create]
  before_action :set_application, only: %i[new create destroy]

  def index
    @members = ::Partner::Partner.joins(applications: :partners).where(
      'developer_partners_oauth_applications_join.partner_id = ?', current_partner.id
    ).uniq
  end

  def new; end

  def create
    partner = Partner::Partner.find_by_email(member_params[:email])
    if @application.has_member?(partner.try(:id))
      redirect_to oauth_applications_path, notice: 'Already join as members'
    else
      payload = {
        name: "#{@application.owner.name}-Developer",
        address: @application.owner.address,
        city: @application.owner.city,
        state: @application.owner.state,
        country: @application.owner.country,
        postcode: @application.owner.postcode,
        overview: @application.owner.overview,
        website_url: @application.owner.website_url,
        password: '12345678'
      }

      if partner.present?
        @application.add_to_members(member_id: partner.id)
        redirect_to oauth_applications_path, notice: 'Member successfully invited'
      else
        @member = ::Partner::Partner.new(member_params.merge(payload))
        if @member.save
          @application.add_to_members(member_id: @member.id)
          redirect_to oauth_applications_path, notice: 'Member invited, please check member email for confirmation'
        else
          redirect_to oauth_applications_path, alert: @member.errors.full_messages.first
        end
      end
    end
  end

  def arl_details
    @api_requ_log = ::Partner::ApiRequestLog.find_by_id(params[:arl_id])
  end

  def destroy
    application = ::Partner::Application.find_by_id(params[:application_id])
    dev_partner = ::Partner::DeveloperPartner.find_by_partner_id_and_application_id(params[:id], application.try(:id))
    if dev_partner.present? && (params[:id].to_i != application.owner_id)
      dev_partner.destroy
      redirect_to oauth_application_path(application.try(:id)), notice: 'Member successfully remove from application'
    else
      redirect_to oauth_application_path(application.try(:id)), alert: 'Opss! Can not remove members from application'
    end
  end

  private

  def member_params
    params.require(:members).permit(:email, :mobile_phone)
  end

  def set_application
    @application = ::Partner::Application.find_by_uid(params[:uid])
  end
end

app/controllers/partner/oauth_applications_controller.rb
class Partner::OauthApplicationsController < Partner::BaseController
  before_action :set_application, only: %i[show edit update destroy]
  before_action :available_scopes, only: %i[new create edit update]
  before_action :available_ocpi_scopes, only: %i[ocpi_new ocpi_create ocpi_edit ocpi_update]

  def index
    @applications = current_partner.applications.order(id: :desc)
    @pagy, @applications = pagy(@applications, items: 5)
  end

  def new
    @application = current_partner.oauth_applications.new
  end

  def create
    @application = current_partner.oauth_applications.new(application_params)

    if @application.save
      flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications create])
      redirect_to oauth_applications_url
    else
      flash[:alert] = @application.errors.full_messages.first
      render :new
    end
  end

  def edit; end

  def update
    if @application.update(application_params)
      flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications update])
      redirect_to oauth_applications_url
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications destroy]) if @application.destroy

    redirect_to oauth_applications_url
  end

  def show
    @pagy, @access_tokens = pagy(@application.access_tokens, items: 5)
    @pagy_member, @members = pagy(@application.partners, items: 5)
  end

  def ocpi_modules
    @ocpi_modules = Ocpi::Domain::Versions::Models::Endpoint.joins(
      version_detail: {
        version: :credential
      }
    )
                                                            .where('ocpi_credentials.id = ?', params[:ocpi_credentials_id])
  end

  private

  def set_application
    @application = current_partner.applications.find_by_id(params[:id])
    return unless @application.blank?

    flash[:alert] = 'Applications not found or you do not have access'
    redirect_to partner_root_path and return
  end

  def available_scopes
    @scopes = [:ocpi_request]
  end

  def application_params
    params[:partner_application][:scopes] = 'ocpi_request' if params[:partner_application][:scopes].blank?
    if params[:partner_application][:scopes].include? :ocpi_token_c
      params[:partner_application][:scopes] = params[:partner_application][:scopes].reject do |scope|
        scope == :ocpi_token_c
      end
    end
    params.require(:partner_application).permit(:credentials_token_a, :ocpi_version_endpoint, :name, scopes: [])
  end
end

app/controllers/partner/ocpi_credentials_controller.rb
class Partner::OcpiCredentialsController < Partner::BaseController
  before_action :set_application, only: %i[show edit update destroy]
  before_action :available_scopes, only: %i[new create edit update]
  before_action :available_ocpi_scopes, only: %i[ocpi_new ocpi_create ocpi_edit ocpi_update]

  def index
    @applications = current_partner.applications.order(id: :desc)
    @pagy, @applications = pagy(@applications, items: 5)
  end

  def new
    @application = current_partner.oauth_applications.new
  end

  def create
    @application = current_partner.oauth_applications.new(application_params)

    if @application.save
      flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications create])
      redirect_to oauth_applications_url
    else
      render :new
    end
  end

  def edit; end

  def update
    if @application.update(application_params)
      flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications update])
      redirect_to oauth_applications_url
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications destroy]) if @application.destroy

    redirect_to oauth_applications_url
  end

  def show
    @access_tokens = @application.access_tokens
    @members       = @application.partners
  end

  def ocpi_modules
    @ocpi_modules = Ocpi::Domain::Versions::Models::Endpoint.joins(
      version_detail: {
        version: :credential
      }
    )
                                                            .where('ocpi_credentials.id = ?', params[:ocpi_credentials_id])
  end

  private

  def set_application
    @application = current_partner.applications.find_by_id(params[:id])
    return unless @application.blank?

    flash[:alert] = 'Applications not found or you do not have access'
    redirect_to partner_root_path and return
  end

  def available_scopes
    @scopes = [:ocpi_request]
  end

  def application_params
    params[:partner_application][:scopes] = 'ocpi_request' if params[:partner_application][:scopes].blank?
    if params[:partner_application][:scopes].include? :ocpi_token_c
      params[:partner_application][:scopes] = params[:partner_application][:scopes].reject do |scope|
        scope == :ocpi_token_c
      end
    end
    params.require(:partner_application).permit(:credentials_token_a, :ocpi_version_endpoint, :name, scopes: [])
  end
end

app/views/partner/oauth_applications/_applications_table.html.erb
<div class="flow-root">
  <div class="-mx-4 -my-2 sm:-mx-6 lg:-mx-8 overflow-x-auto">
    <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
      <table class="min-w-full divide-y divide-gray-300">
        <thead>
          <tr>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">ID</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">NAME</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">STATUS</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">ACTION</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <% @applications.each do |app| %>
          <tr>
            <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= app.id %></td>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= app.name %></td>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= app.approved_by_admin ? 'Approved' : 'Waiting for approval'%></td>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
            <%= link_to oauth_application_path(app), class: "inline-flex items-center rounded border border-transparent bg-indigo-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
              <label>Show</label>
            <% end %>
            <% if (app.is_ocpi? && !app.approved_by_admin) || !app.is_ocpi? %>
              <%= link_to edit_oauth_application_path(app), class: "inline-flex items-center rounded border border-transparent bg-green-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2" do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                </svg>
                <label>Edit</label>
              <% end %>
            <% end %>
            <% if current_partner.is_owner?(app.try(:id)) && !app.approved_by_admin?%>
              <%= link_to oauth_application_path(app), data: { turbo_confirm: "Are you sure?", turbo_method: :delete }, class: "inline-flex items-center rounded border border-transparent bg-red-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2" do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                </svg>
                <label>Delete</label>
              <% end %>
            <% end %>
            <%
=begin%>
 <%= link_to oauth_application_path(app), class: "inline-flex items-center rounded border border-transparent bg-amber-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-amber-700 focus:outline-none focus:ring-2 focus:ring-amber-500 focus:ring-offset-2" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zM4 19.235v-.11a6.375 6.375 0 0112.75 0v.109A12.318 12.318 0 0110.374 21c-2.331 0-4.512-.645-6.374-1.766z" />
              </svg>
              <label>Invite Members</label>
            <% end %> 
<%
=end%>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= render 'shared/partner/pagination', data: { pagy: @pagy } %>
    </div>
  </div>
</div>

app/views/partner/oauth_applications/_table.html.erb
<div class="flow-root">
  <div class="-mx-4 -my-2 sm:-mx-6 lg:-mx-8 overflow-x-auto">
    <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
      <table class="min-w-full divide-y divide-gray-300">
        <thead>
          <tr>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">NO</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">ACCESS TOKEN</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">STATUS</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">SCOPES</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">ACTION</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <% if @access_tokens.present? %>
            <% @access_tokens.each.with_index(1) do |access_token, idx| %>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= idx %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= access_token.token %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= access_token.revoked_at.blank? ? 'Active' : 'Non-active'%></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= access_token.scopes %></td>
                <td class="relative items-center whitespace-nowrap py-4 pl-3 pr-4 text-left text-sm font-medium sm:pr-0">
                  <% if access_token.scopes.include?('ocpi_request') %>
                    <%= link_to partner_tokens_ocpi_connect_path(token: access_token.token), data: { turbo_method: :post }, class: "inline-flex items-center rounded border border-transparent bg-green-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2" do %>
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M5.636 5.636a9 9 0 1012.728 0M12 3v9" />
                      </svg>
                      <label>Connect with HUB!</label>
                    <% end %>
                  <% end %>
                  <% if @application.is_ocpi? && @application.ocpi_connected? && @application.approved_by_admin %>
                    <%#= link_to 'View OCPI Modules', ocpi_modules_admin_partner_oauth_application_path(@partner, @application, ocpi_credentials_id: access_token.ocpi_credentials_id), class: "inline-flex items-center rounded border border-transparent bg-green-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2" %>
                    <%= link_to partner_tokens_ocpi_disconnect_path(token: access_token.token), data: { turbo_method: :delete, turbo_confirm: 'Are you sure to Disconnect?' }, method: :delete, class: "inline-flex items-center rounded border border-transparent bg-red-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2" do %>
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M5.636 5.636a9 9 0 1012.728 0M12 3v9" />
                      </svg>
                      <label>Disconnect with HUB!</label>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% else %>
           <tr><td colspan='5' class="text-center whitespace-nowrap px-3 py-4 text-sm text-gray-500">No Data Access Token</td></tr>
          <% end %>
        </tbody>
      </table>
      <%= render 'shared/pagination', data: { pagy: pagy } %>
    </div>
  </div>
</div>

app/views/partner/oauth_applications/create.turbo_stream.html.erb
<%= render_turbo_stream_flash_messages %>

app/views/partner/oauth_applications/edit.html.erb
<div class="flex flex-col">
  <div class="rounded-lg bg-white shadow flex-grow">
    <!-- header content begin -->
    <div class="px-4 py-3 sm:px-6 md:sticky md:top-16 md:z-10 bg-white rounded-t-lg border-b">
      <div class="sm:flex sm:items-center">
        <div class="mt-4 sm:mt-0 sm:flex-none">
          <h1 class="text-base font-semibold leading-6 text-gray-900">Edit Application</h1>
        </div>
      </div>
    </div>
    <!-- header content end -->

    <div class="px-4 py-5 sm:p-6 flex-grow">
      <!-- table content begin -->
      <%= render partial: 'form', locals: { url: oauth_applications_path, method: 'POST', scopes: @scopes }%>
      <!-- table content end -->
    </div>
  </div>
</div>