config/routes.rb
Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check
  resources :connectors, only: %i[index show]
  resources :evses, only: %i[index show]
  resources :locations, only: %i[index show]
  resources :credentials, only: %i[index show]
  resources :logs, only: %i[index show]
  resources :client_infos, only: [:index]
  get 'locations/show'
  mount Ocpi::Engine => '/'
  get '/' => 'home#index'
  get '/table' => 'home#table'
  root to: 'home#index'
  devise_for :users
  # Admin routes
  namespace :admin do
    resources :partners, controller: 'partner/partners', only: %i[index show edit update] do
      member do
        put '/push/', to: 'partner/partners#push_charger_group', as: :push_charger_group
        put '/download/', to: 'partner/partners#download_charger_group', as: :download_charger_group
      end

      resources :oauth_applications, controller: 'partner/oauth_applications', except: %i[index destroy] do
        member do
          get :approve
          get :validate
          post :receive_push
          get :ocpi_disconnect
          get :ocpi_modules
        end
      end
    end

    resources :admins
  end

  devise_for :partners, class_name: 'Partner::Partner', controllers: {
    sessions: 'partner/devise/sessions',
    passwords: 'partner/devise/passwords',
    registrations: 'partner/devise/registrations',
    confirmations: 'partner/devise/confirmations',
    unlocks: 'partner/devise/unlocks'
  }

  use_doorkeeper scope: 'partner' do
    controllers applications: 'partner/oauth_applications'
    controllers authorizations: 'partner/authorizations'
    controllers tokens: 'partner/tokens'
  end

  namespace :partner do
    root 'dashboard#index'
    post '/tokens/ocpi_request' => 'tokens#ocpi_request'
    post '/tokens/ocpi_connect' => 'tokens#ocpi_connect'
    delete '/tokens/ocpi_disconnect' => 'tokens#ocpi_disconnect'
  end
end

app/models/cdr.rb
class Cdr < Ocpi::Domain::Cdrs::Models::Cdr
end

app/models/cdr_dimension.rb
class CdrDimension < Ocpi::Domain::Common::Models::CdrDimension
end

app/models/cdr_token.rb
class CdrToken < Ocpi::Domain::Common::Models::CdrToken
end

app/models/connector.rb
class Connector < Ocpi::Domain::Locations::Models::Connector
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/credential.rb
class Credential < Ocpi::Domain::Credentials::Models::Credential
end

app/models/evse.rb
class Evse < Ocpi::Domain::Locations::Models::Evse
end

app/models/geo_location.rb
class GeoLocation < Ocpi::Domain::Locations::Models::GeoLocation
end

app/models/hour.rb
class Hour < Ocpi::Domain::Locations::Models::Hour
end

app/models/image.rb
class Image < Ocpi::Domain::Common::Models::Image
end

app/models/location.rb
class Location < Ocpi::Domain::Locations::Models::Location
end

app/models/logs_db.rb
class LogsDb < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :logs_db, reading: :logs_db }
end

app/models/price.rb
class Price < Ocpi::Domain::Common::Models::Price
end

app/models/regular_hour.rb
class RegularHour < Ocpi::Domain::Locations::Models::RegularHour
end

app/models/session.rb
class Session < Ocpi::Domain::Sessions::Models::Session
end

app/models/stop_session.rb
class StopSession < Ocpi::Domain::Commands::Models::StopSession
end

app/models/tariff.rb
class Tariff < Ocpi::Domain::Tariffs::Models::Tariff
end

app/models/token.rb
class Token < Ocpi::Domain::Tokens::Models::Token
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  def self.ransackable_attributes(_auth_object = nil)
    %w[confirmation_sent_at confirmation_token confirmed_at created_at current_sign_in_at
       current_sign_in_ip email encrypted_password failed_attempts id last_sign_in_at last_sign_in_ip locked_at remember_created_at reset_password_sent_at reset_password_token sign_in_count unconfirmed_email unlock_token updated_at]
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  layout 'admin'

  def index
    @q = Partner::ApiRequestLog.order('created_at desc').ransack(params[:q])
    @pagy, @logs = pagy(@q.result(distinct: true), items: 10)
  end

  def show
    @log = Partner::ApiRequestLog.find_by(id: params[:id])
  end

  private

  def set_log; end
end

app/helpers/evses_helper.rb
module EvsesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/index/_search.html.erb
<%= search_form_for @q, url: logs_path, class: "space-y-8 divide-y divide-gray-200" do |f| %>
  <div class="space-y-8 divide-y divide-gray-200">
    <div class="">
      <div class="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-2">
          <label for="city" class="block text-sm font-medium text-gray-700">Request Type</label>
          <div class="mt-1">
            <%= f.select :request_type_eq, options_for_select([["INCOMING", 0], ["OUTGOING", 1]], selected: @q.request_type_eq), { include_blank: true }, { class: 'mt-1 block w-full rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm' } %>
            <%= hidden_field_tag :party_id, params[:party_id] %>
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="region" class="block text-sm font-medium text-gray-700">Status</label>
          <div class="mt-1">
            <%= f.select :status_code_eq, options_for_select([["200", "200"], ["500", "500"], ["400", "400"], ["422", "422"]], selected: @q.status_code_eq), { include_blank: true }, { class: 'mt-1 block w-full rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm' } %>
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="region" class="block text-sm font-medium text-gray-700">Description</label>
          <div class="mt-1">
             <%= f.search_field :description_cont, placeholder: "Search Description", class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"%>
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="region" class="block text-sm font-medium text-gray-700">Endpoint</label>
          <div class="mt-1">
             <%= f.search_field :endpoint_cont, placeholder: "Search Endpoint", class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"%>
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="region" class="block text-sm font-medium text-gray-700">Partner</label>
          <div class="mt-1">
             <%= f.search_field :oauth_application_name_cont, placeholder: "Search Partner", class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"%>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="pt-5">
    <div class="flex justify-start">
      <%= f.button 'Search', class: "inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
      <%= link_to 'Clear Search', logs_path, class: "ml-3 rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    </div>
  </div>
<% end %>

app/views/logs/index/_table.html.erb
<div class="flow-root overflow-x-auto">
  <div class="-mx-4 -my-2 sm:-mx-6 lg:-mx-8 overflow-x-auto">
    <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
      <table class="min-w-full divide-y divide-gray-300">
        <thead class='uppercase'>
          <tr>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Id</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Request Type</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Description</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Endpoint</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Partner</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Date</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <% if @logs.present? %>
            <% @logs.each do |log| %>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
                  <%= link_to "#{log.id}", log_path(log.id), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= log.request_type.to_s.upcase  %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= log.description %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <span class="inline-flex items-center rounded-full <%=log.status_code.in?(['200', '201']) ? 'bg-green-100' : 'bg-red-100'%> px-2.5 py-0.5 text-xs font-medium text-<%=log_class(log.status_code)%>-800">
                    <svg class="-ml-0.5 mr-1.5 h-2 w-2 <%=log.status_code.in?(['200', '201']) ? 'text-green-400' : 'text-red-400'%>" fill="currentColor" viewBox="0 0 8 8">
                      <circle cx="4" cy="4" r="3" />
                    </svg>
                    <%= "#{log.status_code}" %>
                  </span>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= log.endpoint.to_s.truncate(45) %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= log.oauth_application&.name %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= log.created_at.strftime("%d-%m-%y - %H:%M:%S") %></td>
              </tr>
            <% end %>
          <% else %>
            <tr class='text-center'><td colspan='7' class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">No Logs Data</td></tr>
          <% end %>
        </tbody>
      </table>
      <%= render 'shared/pagination', data: { pagy: pagy } %>
    </div>
  </div>
</div>