config/routes.rb
Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check
  resources :connectors, only: %i[index show]
  resources :evses, only: %i[index show]
  resources :locations, only: %i[index show]
  resources :credentials, only: %i[index show]
  resources :logs, only: %i[index show]
  resources :client_infos, only: [:index]
  get 'locations/show'
  mount Ocpi::Engine => '/'
  get '/' => 'home#index'
  get '/table' => 'home#table'
  root to: 'home#index'
  devise_for :users
  # Admin routes
  namespace :admin do
    resources :partners, controller: 'partner/partners', only: %i[index show edit update] do
      member do
        put '/push/', to: 'partner/partners#push_charger_group', as: :push_charger_group
        put '/download/', to: 'partner/partners#download_charger_group', as: :download_charger_group
      end

      resources :oauth_applications, controller: 'partner/oauth_applications', except: %i[index destroy] do
        member do
          get :approve
          get :validate
          post :receive_push
          get :ocpi_disconnect
          get :ocpi_modules
        end
      end
    end

    resources :admins
  end

  devise_for :partners, class_name: 'Partner::Partner', controllers: {
    sessions: 'partner/devise/sessions',
    passwords: 'partner/devise/passwords',
    registrations: 'partner/devise/registrations',
    confirmations: 'partner/devise/confirmations',
    unlocks: 'partner/devise/unlocks'
  }

  use_doorkeeper scope: 'partner' do
    controllers applications: 'partner/oauth_applications'
    controllers authorizations: 'partner/authorizations'
    controllers tokens: 'partner/tokens'
  end

  namespace :partner do
    root 'dashboard#index'
    post '/tokens/ocpi_request' => 'tokens#ocpi_request'
    post '/tokens/ocpi_connect' => 'tokens#ocpi_connect'
    delete '/tokens/ocpi_disconnect' => 'tokens#ocpi_disconnect'
  end
end

app/models/partner/developer_partner.rb
class Partner::DeveloperPartner < ApplicationRecord
  belongs_to :partner
  belongs_to :application
end

app/controllers/admin/partner/oauth_applications_controller.rb
class Admin::Partner::OauthApplicationsController < AdminController
  before_action :set_partner
  before_action :set_application

  def show
    @pagy, @access_tokens = pagy(@application.access_tokens, items: 5)
  end

  def edit; end

  def update
    if @application.update(application_params)
      redirect_to admin_partner_oauth_application_path(partner_id: @partner.id, id: @application.id),
                  flash: { success: 'Application successfully updated.' }
    else
      render :edit
    end
  end

  def approve
    if @application.present?
      @application.update(approved_by_admin: true)
      # @partner.create_user_charging_session if @partner.user.blank?
      redirect_to admin_partner_oauth_application_path(partner_id: @partner.id, id: @application.id),
                  flash: { success: 'Application successfully approved.' }
    else
      redirect_to admin_partner_path(@partner), flash: { error: 'Application failed to approve.' }
    end
  end

  def validate
    # verify their version
    ocpi_configuration = Ocpi::Application::Credentials::Services::FetchVersion.new(token: @application.credentials_token_a)
    result = ocpi_configuration.call(url: @application.ocpi_version_endpoint)
    if ocpi_configuration.valid?
      @application.update(ocpi_validation_status: :ocpi_valid)
      flash[:success] = I18n.t(:notice, scope: %i[doorkeeper flash applications ocpi valid])
    else
      flash[:error] = I18n.t(:notice, scope: %i[doorkeeper flash applications ocpi invalid])
    end
    redirect_to admin_partner_oauth_application_path(partner_id: @partner.id, id: @application.id)
  rescue StandardError => e
    flash[:error] = I18n.t(:notice, scope: %i[doorkeeper flash applications ocpi invalid]) + ' => ' + e.to_s
    redirect_to admin_partner_oauth_application_path(partner_id: @partner.id, id: @application.id)
  end

  def receive_push
    if @application.update(receive_push_model: params[:receive_push_model])
      status = params[:receive_push_model] == 'true' ? 'resumed' : 'paused'
      redirect_to admin_partner_oauth_application_path(partner_id: @partner.id, id: @application.id),
                  flash: { success: "Push Model successfully #{status}" }
    else
      redirect_to admin_partner_oauth_application_path(partner_id: @partner.id, id: @application.id),
                  flash: { error: 'Something went wrong' }
    end
  end

  def ocpi_modules
    @their_token = Ocpi::Domain::Credentials::Models::Credential.find params[:ocpi_credentials_id]
    @ocpi_modules = Ocpi::Domain::Versions::Models::Endpoint.joins(
      version_detail: {
        version: :credential
      }
    )
                                                            .where('ocpi_credentials.id = ?', params[:ocpi_credentials_id])
                                                            .order(identifier: :asc)
  end

  private

  def set_partner
    @partner = ::Partner::Partner.find_by_id(params[:partner_id])
  end

  def set_application
    @application = @partner.oauth_applications.find_by_id(params[:id])
  end

  def application_params
    params.require(:partner_application).permit(:name, :redirect_uri, :scopes, :confidential, :payment_gateway_webhook,
                                                :status_notification_webhook)
  end
end

app/controllers/admin/partner/partners_controller.rb
class Admin::Partner::PartnersController < AdminController
  before_action :set_partner, only: %i[show edit update]

  def index
    @q = Partner::Partner.ransack(params[:q])
    @pagy, @partners = pagy(@q.result(distinct: true), items: 5)
  end

  def show
    @applications = @partner.oauth_applications.order(id: :desc) # .page(params[:page])
  end

  def edit; end

  def update
    if @partner.update(partner_params)
      # @partner.generate_partner_charger_group(params[:partner_charger_groups])
      redirect_to admin_partners_path, flash: { success: 'Partner updated successfully.' }
    else
      render :edit
    end
  end

  private

  def set_partner
    @partner = Partner::Partner.find_by(id: params[:id])
  end

  def partner_params
    params.require(:partner_partner).permit(:code, :name, :address, :city, :state, :country, :postcode,
                                            :overview, :registration_no, :website_url, :logo, :email, :mobile_phone, :user_id, :party_id,
                                            :country_code, :ocpi_percentage_fee, :charger_group_option, :partner_charger_groups)
  end
end

app/controllers/partner/authorizations_controller.rb
class Partner::AuthorizationsController < Doorkeeper::AuthorizationsController
  skip_forgery_protection
  before_action :get_application, only: %i[create destroy]
  before_action :previous_path

  def create
    if @application.approved_by_admin?
      authorization = ::Partner::AccessGrant.new(redirect_uri: @application.redirect_uri,
                                                 application_id: @application.id, expires_in: 3600, resource_owner_id: @application.owner.id, scopes: @application.scopes)
      @authorization = if authorization.save
                         { message: 'Your application authorized!', is_success: true,
                           authorization_code: authorization.token }
                       else
                         { message: 'Something went wrong!', is_success: false, authorization_code: nil }
                       end
    else
      @authorization = { message: 'You do not have authorization to access. <br> Waiting for Approval',
                         is_success: false, authorization_code: nil }
    end
  end

  def show
    @access_grant = ::Partner::AccessGrant.find_by_token(params[:code])
  end

  def destroy
    access_grant = ::Partner::AccessGrant.find_by_id(params[:id])
    access_grant.destroy
    redirect_to oauth_application_path(@application.id), notice: 'Successfully destroyed'
  end

  private

  def get_application
    @application = ::Partner::Application.find_by_uid(params[:client_id])
    return unless @application.blank?

    @authorization = { message: 'Application not found', is_success: false,
                       authorization_code: nil }
  end

  def previous_path
    @previous_path = params[:previous_path]
  end
end

app/controllers/partner/base_controller.rb
class Partner::BaseController < ActionController::Base
  include Pagy::Backend

  layout 'partner'
  before_action :authenticate_partner!

  def authenticate_partner!
    return if partner_signed_in?

    redirect_to new_partner_session_path
  end

  def render_turbo_flash
    turbo_stream.update('flash', partial: 'shared/flash')
  end
end

app/controllers/partner/dashboard_controller.rb
class Partner::DashboardController < Partner::BaseController
  def index
    current_partner_apps = current_partner.applications.pluck(:id)
    # unless current_partner_apps.blank?
    #   @api_req_log_today = ::Partner::ApiRequestLog.by_today(current_partner_apps).page(params[:by_today]).per(5)
    #   @api_req_log_this_week  = ::Partner::ApiRequestLog.by_this_week(current_partner_apps).page(params[:by_this_week]).per(5)
    #   @api_req_log_this_month = ::Partner::ApiRequestLog.by_this_months(current_partner_apps).page(params[:by_this_months]).per(5)
    # end
  end

  def arl_details
    @api_requ_log = ::Partner::ApiRequestLog.find_by_id(params[:arl_id])
  end
end

app/controllers/partner/members_controller.rb
class Partner::MembersController < Partner::BaseController
  layout 'partner'
  skip_before_action :authenticate_partner!, only: %i[new create]
  before_action :set_application, only: %i[new create destroy]

  def index
    @members = ::Partner::Partner.joins(applications: :partners).where(
      'developer_partners_oauth_applications_join.partner_id = ?', current_partner.id
    ).uniq
  end

  def new; end

  def create
    partner = Partner::Partner.find_by_email(member_params[:email])
    if @application.has_member?(partner.try(:id))
      redirect_to oauth_applications_path, notice: 'Already join as members'
    else
      payload = {
        name: "#{@application.owner.name}-Developer",
        address: @application.owner.address,
        city: @application.owner.city,
        state: @application.owner.state,
        country: @application.owner.country,
        postcode: @application.owner.postcode,
        overview: @application.owner.overview,
        website_url: @application.owner.website_url,
        password: '12345678'
      }

      if partner.present?
        @application.add_to_members(member_id: partner.id)
        redirect_to oauth_applications_path, notice: 'Member successfully invited'
      else
        @member = ::Partner::Partner.new(member_params.merge(payload))
        if @member.save
          @application.add_to_members(member_id: @member.id)
          redirect_to oauth_applications_path, notice: 'Member invited, please check member email for confirmation'
        else
          redirect_to oauth_applications_path, alert: @member.errors.full_messages.first
        end
      end
    end
  end

  def arl_details
    @api_requ_log = ::Partner::ApiRequestLog.find_by_id(params[:arl_id])
  end

  def destroy
    application = ::Partner::Application.find_by_id(params[:application_id])
    dev_partner = ::Partner::DeveloperPartner.find_by_partner_id_and_application_id(params[:id], application.try(:id))
    if dev_partner.present? && (params[:id].to_i != application.owner_id)
      dev_partner.destroy
      redirect_to oauth_application_path(application.try(:id)), notice: 'Member successfully remove from application'
    else
      redirect_to oauth_application_path(application.try(:id)), alert: 'Opss! Can not remove members from application'
    end
  end

  private

  def member_params
    params.require(:members).permit(:email, :mobile_phone)
  end

  def set_application
    @application = ::Partner::Application.find_by_uid(params[:uid])
  end
end

app/controllers/partner/oauth_applications_controller.rb
class Partner::OauthApplicationsController < Partner::BaseController
  before_action :set_application, only: %i[show edit update destroy]
  before_action :available_scopes, only: %i[new create edit update]
  before_action :available_ocpi_scopes, only: %i[ocpi_new ocpi_create ocpi_edit ocpi_update]

  def index
    @applications = current_partner.applications.order(id: :desc)
    @pagy, @applications = pagy(@applications, items: 5)
  end

  def new
    @application = current_partner.oauth_applications.new
  end

  def create
    @application = current_partner.oauth_applications.new(application_params)

    if @application.save
      flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications create])
      redirect_to oauth_applications_url
    else
      flash[:alert] = @application.errors.full_messages.first
      render :new
    end
  end

  def edit; end

  def update
    if @application.update(application_params)
      flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications update])
      redirect_to oauth_applications_url
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications destroy]) if @application.destroy

    redirect_to oauth_applications_url
  end

  def show
    @pagy, @access_tokens = pagy(@application.access_tokens, items: 5)
    @pagy_member, @members = pagy(@application.partners, items: 5)
  end

  def ocpi_modules
    @ocpi_modules = Ocpi::Domain::Versions::Models::Endpoint.joins(
      version_detail: {
        version: :credential
      }
    )
                                                            .where('ocpi_credentials.id = ?', params[:ocpi_credentials_id])
  end

  private

  def set_application
    @application = current_partner.applications.find_by_id(params[:id])
    return unless @application.blank?

    flash[:alert] = 'Applications not found or you do not have access'
    redirect_to partner_root_path and return
  end

  def available_scopes
    @scopes = [:ocpi_request]
  end

  def application_params
    params[:partner_application][:scopes] = 'ocpi_request' if params[:partner_application][:scopes].blank?
    if params[:partner_application][:scopes].include? :ocpi_token_c
      params[:partner_application][:scopes] = params[:partner_application][:scopes].reject do |scope|
        scope == :ocpi_token_c
      end
    end
    params.require(:partner_application).permit(:credentials_token_a, :ocpi_version_endpoint, :name, scopes: [])
  end
end

app/controllers/partner/ocpi_credentials_controller.rb
class Partner::OcpiCredentialsController < Partner::BaseController
  before_action :set_application, only: %i[show edit update destroy]
  before_action :available_scopes, only: %i[new create edit update]
  before_action :available_ocpi_scopes, only: %i[ocpi_new ocpi_create ocpi_edit ocpi_update]

  def index
    @applications = current_partner.applications.order(id: :desc)
    @pagy, @applications = pagy(@applications, items: 5)
  end

  def new
    @application = current_partner.oauth_applications.new
  end

  def create
    @application = current_partner.oauth_applications.new(application_params)

    if @application.save
      flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications create])
      redirect_to oauth_applications_url
    else
      render :new
    end
  end

  def edit; end

  def update
    if @application.update(application_params)
      flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications update])
      redirect_to oauth_applications_url
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = I18n.t(:notice, scope: %i[doorkeeper flash applications destroy]) if @application.destroy

    redirect_to oauth_applications_url
  end

  def show
    @access_tokens = @application.access_tokens
    @members       = @application.partners
  end

  def ocpi_modules
    @ocpi_modules = Ocpi::Domain::Versions::Models::Endpoint.joins(
      version_detail: {
        version: :credential
      }
    )
                                                            .where('ocpi_credentials.id = ?', params[:ocpi_credentials_id])
  end

  private

  def set_application
    @application = current_partner.applications.find_by_id(params[:id])
    return unless @application.blank?

    flash[:alert] = 'Applications not found or you do not have access'
    redirect_to partner_root_path and return
  end

  def available_scopes
    @scopes = [:ocpi_request]
  end

  def application_params
    params[:partner_application][:scopes] = 'ocpi_request' if params[:partner_application][:scopes].blank?
    if params[:partner_application][:scopes].include? :ocpi_token_c
      params[:partner_application][:scopes] = params[:partner_application][:scopes].reject do |scope|
        scope == :ocpi_token_c
      end
    end
    params.require(:partner_application).permit(:credentials_token_a, :ocpi_version_endpoint, :name, scopes: [])
  end
end

app/views/admin/partners/shared/_header_detail.html.erb
<div class="overflow-hidden bg-white">
  <%
=begin%>
 <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg font-medium leading-6 text-gray-900">Applicant Information</h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500">Personal details and application.</p>
  </div> 
<%
=end%>
  <div class="px-4 py-5 sm:px-6">
    <dl class="grid grid-cols-1 gap-x-4 gap-y-4 sm:grid-cols-4">
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Code</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.code %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Registration No</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.registration_no %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Name</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.name %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Email</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.email %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Country</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.country %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">City</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.city %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">State</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.state %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Address</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.address %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Website Url</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.website_url %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Mobile Phone</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.mobile_phone %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Overviw</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.overview %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Created At</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.created_at %></dd>
      </div>
    </dl>
  </div>

  <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
   <h5 class="text-md font-medium leading-6 text-gray-900">User Information</h5>
    <dl class="mt-5 grid grid-cols-1 gap-x-4 gap-y-4 sm:grid-cols-3">
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">ID</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.user&.id %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Email</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.user&.email %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Full Name</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= @partner.user&.name %></dd>
      </div>
    </dl>
  </div>
</div>

app/views/admin/partners/shared/_table.html.erb
<div class="flow-root">
  <div class="-mx-4 -my-2 sm:-mx-6 lg:-mx-8 overflow-x-auto">
    <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
      <table class="min-w-full divide-y divide-gray-300">
        <thead>
          <tr>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">ID</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">CODE</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">NAME</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">EMAIL</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">REGISTRATION NO</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">WEBSITE URL</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">ACTION</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <% @partners.each do |partner| %>
          <tr>
            <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= partner.id %></td>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= partner.code %></td>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= partner.name %></td>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= partner.email %></td>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= partner.registration_no %></td>
            <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= partner.website_url %></td>
            <td class="relative items-center whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
            <%= link_to admin_partner_path(partner), class: "inline-flex items-center rounded border border-transparent bg-indigo-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
              <label>Show</label>
            <% end %>
            <%= link_to edit_admin_partner_path(partner), class: "inline-flex items-center rounded border border-transparent bg-amber-600 px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-amber-700 focus:outline-none focus:ring-2 focus:ring-amber-500 focus:ring-offset-2" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
              </svg>
              <label>Edit</label>
            <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= render 'shared/pagination', data: {} %>
    </div>
  </div>
</div>