config/routes.rb
Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check
  resources :connectors, only: %i[index show]
  resources :evses, only: %i[index show]
  resources :locations, only: %i[index show]
  resources :credentials, only: %i[index show]
  resources :logs, only: %i[index show]
  resources :client_infos, only: [:index]
  get 'locations/show'
  mount Ocpi::Engine => '/'
  get '/' => 'home#index'
  get '/table' => 'home#table'
  root to: 'home#index'
  devise_for :users
  # Admin routes
  namespace :admin do
    resources :partners, controller: 'partner/partners', only: %i[index show edit update] do
      member do
        put '/push/', to: 'partner/partners#push_charger_group', as: :push_charger_group
        put '/download/', to: 'partner/partners#download_charger_group', as: :download_charger_group
      end

      resources :oauth_applications, controller: 'partner/oauth_applications', except: %i[index destroy] do
        member do
          get :approve
          get :validate
          post :receive_push
          get :ocpi_disconnect
          get :ocpi_modules
        end
      end
    end

    resources :admins
  end

  devise_for :partners, class_name: 'Partner::Partner', controllers: {
    sessions: 'partner/devise/sessions',
    passwords: 'partner/devise/passwords',
    registrations: 'partner/devise/registrations',
    confirmations: 'partner/devise/confirmations',
    unlocks: 'partner/devise/unlocks'
  }

  use_doorkeeper scope: 'partner' do
    controllers applications: 'partner/oauth_applications'
    controllers authorizations: 'partner/authorizations'
    controllers tokens: 'partner/tokens'
  end

  namespace :partner do
    root 'dashboard#index'
    post '/tokens/ocpi_request' => 'tokens#ocpi_request'
    post '/tokens/ocpi_connect' => 'tokens#ocpi_connect'
    delete '/tokens/ocpi_disconnect' => 'tokens#ocpi_disconnect'
  end
end

app/models/cdr.rb
class Cdr < Ocpi::Domain::Cdrs::Models::Cdr
end

app/models/cdr_token.rb
class CdrToken < Ocpi::Domain::Common::Models::CdrToken
end

app/models/connector.rb
class Connector < Ocpi::Domain::Locations::Models::Connector
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/credential.rb
class Credential < Ocpi::Domain::Credentials::Models::Credential
end

app/models/evse.rb
class Evse < Ocpi::Domain::Locations::Models::Evse
end

app/models/geo_location.rb
class GeoLocation < Ocpi::Domain::Locations::Models::GeoLocation
end

app/models/hour.rb
class Hour < Ocpi::Domain::Locations::Models::Hour
end

app/models/image.rb
class Image < Ocpi::Domain::Common::Models::Image
end

app/models/location.rb
class Location < Ocpi::Domain::Locations::Models::Location
end

app/models/logs_db.rb
class LogsDb < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :logs_db, reading: :logs_db }
end

app/models/price.rb
class Price < Ocpi::Domain::Common::Models::Price
end

app/models/regular_hour.rb
class RegularHour < Ocpi::Domain::Locations::Models::RegularHour
end

app/models/session.rb
class Session < Ocpi::Domain::Sessions::Models::Session
end

app/models/stop_session.rb
class StopSession < Ocpi::Domain::Commands::Models::StopSession
end

app/models/tariff.rb
class Tariff < Ocpi::Domain::Tariffs::Models::Tariff
end

app/models/token.rb
class Token < Ocpi::Domain::Tokens::Models::Token
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  def self.ransackable_attributes(_auth_object = nil)
    %w[confirmation_sent_at confirmation_token confirmed_at created_at current_sign_in_at
       current_sign_in_ip email encrypted_password failed_attempts id last_sign_in_at last_sign_in_ip locked_at remember_created_at reset_password_sent_at reset_password_token sign_in_count unconfirmed_email unlock_token updated_at]
  end
end

app/helpers/evses_helper.rb
module EvsesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/admin/admins/edit.html.erb
<div class="flex flex-col">
  <div class="rounded-lg bg-white shadow flex-grow">
    <!-- header content begin -->
    <div class="px-4 py-3 sm:px-6 md:sticky md:top-16 md:z-10 bg-white rounded-t-lg border-b">
      <div class="sm:flex sm:items-center">
        <div class="mt-4 sm:mt-0 sm:flex-none">
          <h1 class="text-base font-semibold leading-6 text-gray-900">Edit Admin</h1>
        </div>
      </div>
    </div>
    <!-- header content end -->

    <div class="px-4 py-5 sm:p-6 flex-grow">
      <!-- table content begin -->
      <%= render 'admin/admins/partials/form', locals: { url: admin_admins_path, method: 'PUT'}%>
      <!-- table content end -->
    </div>
  </div>
</div>

app/views/admin/admins/index.html.erb
<!-- Heading Section -->
<div class="md:flex md:items-center md:justify-between mb-5">
  <div class="min-w-0 flex-1">
    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:truncate sm:text-xl sm:tracking-tight">Admins</h2>
  </div>
  <div class="mt-4 flex md:mt-0 md:ml-4">
  </div>
</div>
<!-- End Heading Section -->
<div class="flex flex-col">
  <div class="rounded-lg bg-white shadow flex-grow">
    <div class="px-4 py-5 sm:p-6 flex-grow">
      <%= render 'admin/admins/partials/search' %>
    </div>
  </div>
</div>

<div class="flex flex-col mt-5">
  <div class="rounded-lg bg-white shadow flex-grow">
    <div class="px-4 py-5 sm:px-6 md:sticky md:top-16 md:z-10 bg-white rounded-t-lg border-b">
      <div class="sm:flex sm:items-center">
        <div class="mt-4 sm:mt-0 sm:flex-none">
          <%= link_to 'New Admin', new_admin_admin_path, class: "block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
        </div>
      </div>
    </div>
    <div class="px-4 py-5 sm:p-6 flex-grow">
      <%= render 'admin/admins/partials/table', pagy: @pagy  %>
    </div>
  </div>
</div>

app/views/admin/admins/new.html.erb
<div class="flex flex-col">
  <div class="rounded-lg bg-white shadow flex-grow">
    <!-- header content begin -->
    <div class="px-4 py-3 sm:px-6 md:sticky md:top-16 md:z-10 bg-white rounded-t-lg border-b">
      <div class="sm:flex sm:items-center">
        <div class="mt-4 sm:mt-0 sm:flex-none">
          <h1 class="text-base font-semibold leading-6 text-gray-900">New Admin</h1>
        </div>
      </div>
    </div>
    <!-- header content end -->

    <div class="px-4 py-5 sm:p-6 flex-grow">
      <!-- table content begin -->
      <%= render 'admin/admins/partials/form', locals: { url: admin_admins_path, method: 'POST', scopes: @scopes }%>
      <!-- table content end -->
    </div>
  </div>
</div>

app/views/admin/admins/partials/_form.html.erb
<%= form_for @admin, url: admin_admins_path, method: :put, html: { class: "space-y-3", role: 'form' } do |f| %>
  <div class="space-y-8 divide-y divide-gray-200">
    <div>
      <div class="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-6">
          <label for="name" class="block text-sm font-medium text-gray-700">Email</label>
          <div class="mt-1 flex rounded-md shadow-sm">
            <%= f.text_field :email, disabled: f.object.id.present?, required: true, placeholder: "Enter admin name", class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="pt-5">
    <div class="flex justify-start">
      <%= link_to "Cancel", admin_admins_path, class: "rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
      <%= f.button 'Save', class: "ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    </div>
  </div>
<% end %>

app/views/admin/admins/partials/_search.html.erb
<%= search_form_for @q, url: admin_admins_path, class: "space-y-8 divide-y divide-gray-200" do |f| %>
  <div class="space-y-8 divide-y divide-gray-200">
    <div class="">
      <div class="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-2">
          <label for="city" class="block text-sm font-medium text-gray-700">Email</label>
          <div class="mt-1">
             <%= f.search_field :email_cont, placeholder: "Search Email", class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"%>
          </div>
        </div>
<%
=begin%>
 
        <div class="sm:col-span-2">
          <label for="region" class="block text-sm font-medium text-gray-700">Name</label>
          <div class="mt-1">
             <%= f.search_field :name_cont, placeholder: "Search Name", class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"%>
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="postal-code" class="block text-sm font-medium text-gray-700">Email</label>
          <div class="mt-1">
            <%= f.search_field :email_cont, placeholder: "Search Email", class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
          </div>
        </div> 
<%
=end%>
      </div>
    </div>
  </div>

  <div class="pt-5">
    <div class="flex justify-start">
      <%= f.button 'Search', class: "inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
      <%= link_to 'Clear Search', admin_admins_path, class: "ml-3 rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    </div>
  </div>
<% end %>

app/views/shared/_breadcumb.html.erb
<nav class="flex mb-5" aria-label="Breadcrumb">
  <ol role="list" class="flex items-center space-x-4">
    <%= yield %>
  </ol>
</nav>

app/views/shared/_breadcumb_content.html.erb
<li>
  <div class="flex items-center">
    <!-- Heroicon name: mini/chevron-right -->
    <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
      <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
    </svg>
    <%= link_to url, class: "ml-4 text-sm font-medium text-gray-500 hover:text-gray-700" do %>
      <%= name %>
    <% end %>
  </div>
</li>

app/views/shared/_logo.html.erb
<div class="flex h-16 shrink-0 items-center">
  <%= image_tag 'evc_logo.jpeg', class: 'h-8 w-auto', alt: 'EV Connection' %>
  <h1 class="ml-4 text-gray-700 font-semibold">OCPI Hub Company</h1>
</div>

app/views/shared/_navbar.html.erb
<nav class="flex flex-1 flex-col" data-controller="navigation">
  <ul role="list" class="flex flex-1 flex-col gap-y-7">
    <li>
      <ul role="list" class="-mx-2 space-y-1">
        <li>
          <!-- Current: "bg-gray-50 text-indigo-600", Default: "text-gray-700 hover:text-indigo-600 hover:bg-gray-50" -->
          <%= link_to(root_path, class: "#{sidebar_class(root_path)}") do %>
            <svg class="h-6 w-6 shrink-0 <%= current_page?(root_path) ? 'text-indigo-600' : 'text-gray-400'%>" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
            </svg>
            Dashboard
          <% end %>
        </li>
        <li>
          <%= link_to(locations_path, class: "#{sidebar_class(locations_path)}") do %>
            <svg class="h-6 w-6 shrink-0 <%= current_page?(locations_path) ? 'text-indigo-600' : 'text-gray-400'%> group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/>
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/>
            </svg>
            Locations
          <% end %>
        </li>
        <li>
          <%= link_to(evses_path, class: "#{sidebar_class(evses_path)}") do %>
            <svg class="h-6 w-6 shrink-0 <%= current_page?(evses_path) ? 'text-indigo-600' : 'text-gray-400'%> group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
            </svg>
            Evses
          <% end %>
        </li>
        <li>
          <%= link_to(connectors_path, class: "#{sidebar_class(connectors_path)}") do %>
            <svg class="h-6 w-6 shrink-0 <%= current_page?(connectors_path) ? 'text-indigo-600' : 'text-gray-400'%> group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
            </svg>
            Connectors
          <% end %>
        </li>
        <li>
          <%= link_to(credentials_path, class: "#{sidebar_class(credentials_path)}") do %>
            <svg class="h-6 w-6 shrink-0 <%= current_page?(credentials_path) ? 'text-indigo-600' : 'text-gray-400'%> group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
            </svg>
            Credentials
          <% end %>
        </li>
        <li>
          <%= link_to(client_infos_path, class: "#{sidebar_class(client_infos_path)}") do %>
            <svg class="h-6 w-6 shrink-0 <%= current_page?(client_infos_path) ? 'text-indigo-600' : 'text-gray-400'%> group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
            </svg>
            Clients
          <% end %>
        </li>
        <li>
          <a href="#" class="text-gray-700 hover:text-indigo-600 hover:bg-gray-50 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold">
            <svg class="h-6 w-6 shrink-0  group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
            </svg>
            Tokens
          </a>
        </li>
        <li>
          <a href="#" class="text-gray-700 hover:text-indigo-600 hover:bg-gray-50 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold">
            <svg class="h-6 w-6 shrink-0  group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
            </svg>
            Tariffs
          </a>
        </li>
        <li>
          <a href="#" class="text-gray-700 hover:text-indigo-600 hover:bg-gray-50 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold">
            <svg class="h-6 w-6 shrink-0  group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
            </svg>
            Sessions
          </a>
        </li>
        <li>
          <a href="#" class="text-gray-700 hover:text-indigo-600 hover:bg-gray-50 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold">
            <svg class="h-6 w-6 shrink-0  group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
            </svg>
            CDRs
          </a>
        </li>
        <li>
          <%= link_to(logs_path, class: "#{sidebar_class(logs_path)}") do %>
            <svg class="h-6 w-6 shrink-0 <%= current_page?(logs_path) ? 'text-indigo-600' : 'text-gray-400'%> group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
            </svg>
            Logs
          <% end %>
        </li>
      </ul>
    </li>
    <li>
      <div class="text-xs font-semibold leading-6 text-gray-400">Management</div>
      <ul role="list" class="-mx-2 mt-2 space-y-1">
        <li>
          <!-- Current: "bg-gray-50 text-indigo-600", Default: "text-gray-700 hover:text-indigo-600 hover:bg-gray-50" -->
          <%= link_to(admin_partners_path, class: "#{sidebar_class(admin_partners_path)}") do %>
            <span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg border text-[0.625rem] font-medium bg-white <%= current_page?(admin_partners_path) ? 'text-indigo-600' : 'text-gray-400'%> border-gray-200 group-hover:border-indigo-600 group-hover:text-indigo-600">P</span>
            <span class="truncate">Partners</span>
          <% end %>
        </li>
        <li>
          <a href="#" class="text-gray-700 hover:text-indigo-600 hover:bg-gray-50 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold">
            <span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg border text-[0.625rem] font-medium bg-white text-gray-400 border-gray-200 group-hover:border-indigo-600 group-hover:text-indigo-600">R</span>
            <span class="truncate">Roles</span>
          </a>
        </li>
        <li>
          <%= link_to(admin_admins_path, class: "#{sidebar_class(admin_admins_path)}") do %>
            <span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg border text-[0.625rem] font-medium bg-white text-gray-400 border-gray-200 group-hover:border-indigo-600 group-hover:text-indigo-600">A</span>
            <span class="truncate">Admins</span>
          <% end %>
        </li>
      </ul>
    </li>
    <%
=begin%>
 <li class="mt-auto">
      <a href="#" class="group -mx-2 flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-700 hover:bg-gray-50 hover:text-indigo-600">
        <svg class="h-6 w-6 shrink-0 text-gray-400 group-hover:text-indigo-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.324.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.24-.438.613-.431.992a6.759 6.759 0 010 .255c-.007.378.138.75.43.99l1.005.828c.424.35.534.954.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.57 6.57 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.28c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.02-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.992a6.932 6.932 0 010-.255c.007-.378-.138-.75-.43-.99l-1.004-.828a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.087.22-.128.332-.183.582-.495.644-.869l.214-1.281z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
        Settings
      </a>
    </li> 
<%
=end%>
  </ul>
</nav>